name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MdMarufHossen71
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Dhaka
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_projects_descriptions: yes
